version: '3'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: php
    volumes:
      - ./:/app:delegated
    ports:
      - '8000:80'
    restart: always
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 5000:3306
    environment:
      MYSQL_DATABASE: bcs-test-app
      MYSQL_ROOT_PASSWORD: root
    restart: always
